name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Install dependencies and tools
    - name: Restore dependencies
      run: dotnet restore

    # Install StyleCop.Analyzers for linting
    - name: Install StyleCop.Analyzers
      run: dotnet add package StyleCop.Analyzers --version 1.2.0

    # Run StyleCop analysis (linting)
    - name: Run StyleCop linting
      run: dotnet build --no-restore --configuration Release

    # Install dotnet format tool for automatic fixing
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format

    # Automatically fix code formatting with dotnet format
    - name: Apply code formatting fixes
      run: dotnet format --check --fix

    # Run Prettier using npx to format C# code
    - name: Run Prettier to format C# code
      run: npx prettier --write "**/*.cs"

    # Build the project after formatting
    - name: Build
      run: dotnet build --no-restore

    # Run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
